### ISSUE TITLE
Add Greenhose role ID to the interactive mode

### ISSUE THREAD

**Issue by rkzack** [canonical/ght#139]
Some roles are similarly named, so for folks who lead multiple roles, when using interactive mode, it would be helpful to see the Greenhouse role ID attached to each job in this section. This will ensure the user picks the correct role:

![image](https://user-images.githubusercontent.com/35204816/166713024-f60fc1b5-a933-4d29-a721-7a0ca0f9a3c7.png)

So, for example, in the above screenshot, instead of just:

```DevOps Engineering Manager, DevOps Centre```

it would be great to see:

```[703] DevOps Engineering Manager, DevOps Centre```

**Comment by marinacastejon** [comment]
Hi @tbille we chatted with @ilayda21 , and we agreed that we should ask users or Mark. Do you think it's better to ask Hiring Leads in MM or to share it before with Mark in our next meeting? 
There are 3 questions:
- Is it useful for the majority?
- Is it the best way to show it? (ID before name)
- Should we then show also (for consistency reasons) Job Post ID?

**Comment by marinacastejon** [comment]
@ilayda21 as discussed let me ask in the Hiring Leads channel and see if the job post ID would be useful as well

**Comment by marinacastejon** [comment]
@ilayda21 we can go ahead. Please add Job ID and Job post ID as discussed. Thanks
