### ISSUE TITLE
arm64 builds broken

### ISSUE THREAD

**Issue by degville** [canonical/ght#195]
I have two problems with the arm64 builds, tested on all recent revisions:

1. The published (automatic build?) doesn't include an arm64 binary (of _node_), resulting in the following error:

```
/snap/ght/49/bin/node: 1: ELF: not found
/snap/ght/49/bin/node: 2: Syntax error: word unexpected (expecting ")")
```

2. The snap does successfully build on arm64, but it seems the arm64 Chromium components required for  _puppeteer_ to enable authentication aren't properly integrated. I spent some time trying to solve this myself, but it still results in the following error:

```
 Your Ubuntu One email: ** 
✔ Your password: · **
✔ 2FA authentication code: · **
✔ Authentication completed.
✖ Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (970485).
```

Tested on an Ubuntu 23.04 VM running on an M1 Mac (aarch64) and also from Ubuntu 22.04 on a Raspberry Pi 4.

**Comment by gerwitz** [comment]
Today, I have this same issue with the published snap, on 22.04 via Multipass on an M2 MacBook. Also @evildmp has [the same](https://chat.canonical.com/canonical/pl/s1aasie75pg35yec8stgk698cw).

**Comment by jnsgruk** [comment]
Hmm, odd. I wonder if this [line](https://github.com/canonical/ght/blob/d5b9a177baf3eed262151acefe0328e2eff534ce/snap/snapcraft.yaml#L26) should actually be changed so that `chromium-browser` is staged into the snap?

**Comment by jnsgruk** [comment]
Okay after another quick look - the biggest glaring issue is that we're staging an x64 version of node when building on `arm` :) https://github.com/canonical/ght/blob/d5b9a177baf3eed262151acefe0328e2eff534ce/snap/snapcraft.yaml#L16

**Comment by degville** [comment]
Thanks for updating this @jnsgruk.

I've just tested the new PR and there's still an (unsolvable?) problem in that Puppeteer cannot find an arm64 binary for Chromium within the snap:

`The chromium binary is not available for arm64.`

However, I was able to skip this dependency by adding `PUPPETEER_SKIP_DOWNLOAD` to the override build environment:

```yaml
        build-environment:
            - PUPPETEER_SKIP_DOWNLOAD: true
            - PUPPETEER_EXECUTABLE_PATH: /snap/chromium/current/bin/chromium.launcher
```

Building the snap with the above change worked, and I was able to get past the 2FA with `ght`. I don't have enough GH credentials to test further.

**Comment by jnsgruk** [comment]
Interesting, I didn't run into that - I thought that setting `PUPPETEER_EXECUTABLE_PATH` implied `PUPPETEER_SKIP_DOWNLOAD`, but I'm happy to add it explicitly. I'll do that now :)

**Comment by degville** [comment]
Thanks you! Strange that I had the problem. I should mention I'm running 23.04 on Parallels on a (*cough*) M1 Macbook Pro.

**Comment by gerwitz** [comment]
Part of this problem persists for me on the edge-published snap (built 19 February 2024, including #226). I no longer get an ELF warning, but this remains (on 22.04 via Multipass on an M2 MacBook):

`/snap/ght/65/bin/node: 1: Syntax error: ")" unexpected`
