### ISSUE TITLE
Create city specific replication

### ISSUE THREAD

**Issue by marco-ciatti** [canonical/ght#204]
I'd like to create an automation to repost individual job posts in the same location. Essentally, copying all the details of a specific job post, deleting it and then reposting it.

**Comment by Dampolo03** [comment]
> I'd like to create an automation to repost individual job posts in the same location. Essentally, copying all the details of a specific job post, deleting it and then reposting it.

Hi Marco, I tried to create this initial [PR](https://github.com/canonical/ght/pull/218) regarding this issue. Although, to understand this issue a bit more - `copying all the details of a specific job post, deleting it and then reposting it`, I think the existing `replicate` command takes care of this? According to a discussion with @andesol. Maybe a bit more explanation on this issue could help, if that's not the case? Thanks.
