### ISSUE TITLE
Written interviews are somethings assigned to more people than desired

### ISSUE THREAD

**Issue by ijansky** [canonical/ght#216]
When running the `ght assign -i` command and selecting two graders, the gth tool sometimes picks up interviews that are already assigned to two graders and adds a third one or a fourth one.

**Comment by anthonydillon** [comment]
@andesol would you mind taking a look at this and pull this into Jira with an example candidate link.

**Comment by andesol** [comment]
I haven't been able to replicate this in my (probably simpler) environment. We'll keep an eye anyway

**Comment by anthonydillon** [comment]
I just ran `edge` and it assigned the right amount of people. Do you have an example?

**Comment by anthonydillon** [comment]
Closing for now as I have not seen this for a while.
