### ISSUE TITLE
Add an option to assign Written Interviewers to candidate at the Devskiller or GIA stage

### ISSUE THREAD

**Issue by o-philippe** [canonical/ght#221]
For fast tracks the process is such that the Hiring Lead should have a first scan on academics at the Written Interview before moving the candidate to Devskiller then GIA states, after which Hiring Associates will be assigned to review the Written Interview.

The request is to add Devskiller and GIA states to the options supported by ght assign, in addition to Written Interview and Hold.

**Comment by anthonydillon** [comment]
As discussed today. We have decided the best step is to include the Hold stage in all reqs.
