### ISSUE TITLE
`ght assign` should allow avoiding reassignment of WI if they are already assigned 

### ISSUE THREAD

**Issue by rpocase** [canonical/ght#235]
When running `ght assign -i` I noticed that a WI may get reassigned even if it has an assignee that is in the WI config. While this may be intentional in some cases, i suspect most users would want only to assign new interviews. `ght assign` should have an option to avoid reassigning when an active interviewer is already assigned.

**Comment by anthonydillon** [comment]
GHT should only assign WIs which have a single review which is the hiring lead. If it is assigning when this is not the case this is an issue. Can you confirm?

**Comment by rpocase** [comment]
> GHT should only assign WIs which have a single review which is the hiring lead. If it is assigning when this is not the case this is an issue. Can you confirm?

I can confirm. Currently it always assigns even if a grader is present and its not the hiring lead. E.g. when I run twice in a row it could potentially rotate all WI to new graders. This is definitely configuration dependent. E.g. I have 1 WIer per interview and two graders. If I had 2 WIers per interview this wouldn't have cropped up for me.
