### ISSUE TITLE
Remove colors by default on terminal prompt

### ISSUE THREAD

**Issue by tbille** [canonical/ght#47]
Comment from @amylily1011 
I would suggest not to have a color scheme by default because most people's CLIs are set up with different terminal theme, so what looks nice in this terminal might look unreadable for certain terminal theme. So maybe be explicit somewhere in this document that there is no default color scheme. 

If you would like to add a color scheme you can create a flag "--colour/-c" to enable the color. However, at the moment we don't have a default color scheme yet.

**Comment by anthonydillon** [comment]
All text colour has been removed from the project. only green ticks are left.
